server:
  servlet:
    context-path: '/api'
app:
  datasource:
    jdbc-url: jdbc:postgresql://139.159.201.49:5432/dbtest
    username: postgres
    password: 70706498
    pool-size: 30
spring:
  flyway:
    baseline-on-migrate: true